name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-26]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@2126ae7fc54c9df00dd18f7f18754393182c73cd # v31.9.1
        with:
          extra_nix_config: |
            accept-flake-config = true
            auto-optimise-store = ${{ startsWith(matrix.os, 'macos-') && 'false' || 'true' }}
            sandbox = ${{ startsWith(matrix.os, 'macos-') && 'relaxed' || 'true' }}
      - name: Setup cachix
        uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
        with:
          name: warashi
          extraPullNames: nix-community
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: false # PR でも push して、 main にマージされたときにキャッシュが使えるようにする
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: ./.github/workflows/build-all.sh
      - name: Check disk usage
        if: always()
        run: df -h
