name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-26]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install nix
        uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
        with:
          nix_conf: |
            auto-optimise-store = ${{ startsWith(matrix.os, 'macos-') && 'false' || 'true' }}
            sandbox = false
      - name: Setup cachix
        uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: warashi
          extraPullNames: nix-community
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: false # PR でも push して、 main にマージされたときにキャッシュが使えるようにする
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - run: sh ./.github/workflows/build-all.sh
      - name: Check disk usage
        if: always()
        run: df -h
